web/src/main/java/kz/shop/web/domain/ProductCriteria.java
package kz.shop.web.domain;

import lombok.Getter;
import lombok.Setter;
import java.math.BigDecimal;

@Getter
@Setter
public class ProductCriteria {
    private String name;
    private BigDecimal priceFrom;
    private BigDecimal priceTo;
}

web/src/main/java/kz/shop/web/handlers/CartController.java
package kz.shop.web.handlers;

import kz.shop.client.models.CartItem;
import kz.shop.client.entities.Product;
import lombok.Getter;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.util.ArrayList;
import java.util.List;

@ManagedBean(name = "cartBean")
@SessionScoped
@Getter
@Setter
public class CartController {
    private List<CartItem> items;

    private static final Logger logger = LoggerFactory.getLogger(CartController.class);

    public CartController() {
        items = new ArrayList<>();
    }

    public void addToCart(Product product) {
        logger.info("addToCart");

        int index = exists(product);
        if (index == -1) {
            items.add(new CartItem(product, 1));
        } else {
            int quantity = items.get(index).getQty() + 1;
            items.get(index).setQty(quantity);
        }
    }

    public String delete(Product product) {
        int index = exists(product);
        items.remove(index);
        return "cart?faces-redirect=true";
    }

    public double total() {
        double s = 0;
        for (CartItem item : this.items) {
            s += item.getProduct().getPrice().doubleValue() * item.getQty();
        }
        return s;
    }

    private int exists(Product product) {
        for (int i = 0; i < items.size(); i++) {
            if (items.get(i).getProduct().getId().equals(product.getId())) {
                return i;
            }
        }
        return -1;
    }
}

web/src/main/java/kz/shop/web/handlers/OrderController.java
package kz.shop.web.handlers;

import kz.shop.client.entities.Order;
import kz.shop.ejb.OrderEjb;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import java.util.List;

@ManagedBean(name = "orderBean")
@SessionScoped
public class OrderController {
    @Inject
    OrderEjb orderEjb;

    private static final Logger logger = LoggerFactory.getLogger(OrderController.class);

    public String create(CartController cartBean) {
        logger.info("CreateOrderByBean");
        orderEjb.create(cartBean.getItems());
        return "shop?faces-redirect=true";
    }

    public List<Order> getAll() {
        logger.info("CreateOrderByBean");
        return orderEjb.getAll();
    }
}

web/src/main/java/kz/shop/web/handlers/ProductController.java
package kz.shop.web.handlers;

import kz.shop.client.entities.Product;
import kz.shop.ejb.ProductEjb;
import kz.shop.web.domain.ProductCriteria;
import lombok.Getter;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.math.BigDecimal;
import java.math.MathContext;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

@ManagedBean(name = "productBean")
@ViewScoped
@Getter
@Setter
public class ProductController {
    @Inject
    private ProductEjb productEjb;

    private static final Logger logger = LoggerFactory.getLogger(ProductController.class);

    private ProductCriteria criteria;
    private Product newProduct;
    private Product currentProduct;
    private List<Product> productList;

    @PostConstruct
    private void init() {
        newProduct = new Product();
        currentProduct = new Product();
        productList = new ArrayList<>();
        criteria = new ProductCriteria();
    }

    public void availableList() {
        productList = productEjb.availableList();
    }

    public void search() {
        HashMap<String, String> hmap = new HashMap<>();

        if (criteria.getName() != null && !criteria.getName().isEmpty()) {
            logger.info("criteria.getPriceFrom()" + criteria.getPriceFrom());
            hmap.put("name", criteria.getName());
        }
        if (criteria.getPriceFrom() != null && criteria.getPriceFrom().compareTo(new BigDecimal(0, MathContext.DECIMAL64)) >= 0) {
            logger.info("criteria.getPriceTo()" + criteria.getPriceTo());
            hmap.put("priceFrom", criteria.getPriceFrom().toString());
        }
        if (criteria.getPriceTo() != null && criteria.getPriceTo().compareTo(new BigDecimal(0, MathContext.DECIMAL64)) >= 0) {
            logger.info("criteria.getName()" + criteria.getName());
            hmap.put("priceTo", criteria.getPriceTo().toString());
        }

        logger.info("hmapSize(): " + hmap.size());

        productList = productEjb.getListByCriteria(hmap);
    }

    public void findByById() {
        currentProduct = productEjb.findByPk(currentProduct.getId());
    }

    public String create() {
        logger.info("CreateProduct");

        FacesContext ctx = FacesContext.getCurrentInstance();
        checkAddingValidation(ctx);
        if (ctx.getMessageList().size() > 0) {
            return null;
        }
        logger.info("beforeCreate");
        productEjb.create(newProduct);
        logger.info("afterCreate");

        flashSuccessAndRefreshProduct(ctx);
        return "shop?faces-redirect=true";
    }

    private void flashSuccessAndRefreshProduct(FacesContext ctx) {
        ctx.addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO,
                        "Success",
                        "Product " + newProduct.getName() + " successfully added."));

        newProduct = new Product();
    }

    private void checkAddingValidation(FacesContext ctx) {
        if (newProduct.getName() == null || "".equals(newProduct.getName())) {
            ctx.addMessage("productForm:name",
                    new FacesMessage(FacesMessage.SEVERITY_WARN, "Неверное значение", "Вы должны ввести name"));
        }

        if (newProduct.getPrice() == null || "".equals(newProduct.getPrice())) {
            ctx.addMessage("productForm:price",
                    new FacesMessage(FacesMessage.SEVERITY_WARN, "Неверное значение", "Вы должны ввести price"));
        }

        if (newProduct.getBody() == null || "".equals(newProduct.getBody())) {
            ctx.addMessage("productForm:body",
                    new FacesMessage(FacesMessage.SEVERITY_WARN, "Неверное значение", "Вы должны ввести body"));
        }
    }

    public void clear() {
        criteria = new ProductCriteria();
    }
}

web/src/main/webapp/cart.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://xmlns.jcp.org/jsf/html"
>
<ui:composition template="layouts/app.xhtml">
    <f:metadata>
        <f:viewAction action="#{productBean.availableList}"/>
    </f:metadata>

    <ui:define name="title">Cart</ui:define>
    <ui:define name="content">
        <h:form prependId="false">
            <table border="1" cellpadding="2" cellspacing="2" class="table">
                <tr>
                    <th>Option</th>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Sub Total</th>
                </tr>
                <ui:repeat var="item" value="#{cartBean.items}">
                    <tr>
                        <td align="center">
                            <h:commandLink value="X" action="#{cartBean.delete(item.product)}"></h:commandLink>
                        </td>
                        <td>#{item.product.id}</td>
                        <td>#{item.product.name}</td>
                        <td>#{item.product.price}</td>
                        <td>#{item.qty}</td>
                        <td>#{item.product.price * item.qty}</td>
                    </tr>
                </ui:repeat>
                <tr>
                    <td colspan="5" align="right">Total</td>
                    <td>#{cartBean.total()}</td>
                </tr>
            </table>

            <br/>
            <br/>

        </h:form>

        <div class="container">
            <div class="raw">
                <div class="col-md-6">
                    <h:link value="Continue purchases"
                            outcome="shop"
                            styleClass="btn btn-outline-dark"/>
                </div>
                <div class="col-md-6">
                    <h:form prependId="false">
                        <h:commandButton value="Order Now!"
                                         action="#{orderBean.create(cartBean)}"
                                         type="submit"
                                         styleClass="btn btn-success"
                                         rendered="#{!cartBean.items.isEmpty()}"/>
                    </h:form>
                </div>
            </div>
        </div>
    </ui:define>
</ui:composition>
</html>

web/src/main/webapp/inc/content.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <div class="pt-5 pb-5">
        <ui:insert name="content">
            Shop content
        </ui:insert>
    </div>
</ui:composition>

web/src/main/webapp/inc/footer.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
        <div class="container text-center">
            <small class="text-light">
                <ui:insert name="footer">
                    Neoflex
                </ui:insert>
            </small>
        </div>
    </footer>
</ui:composition>

web/src/main/webapp/inc/header.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <div class="container">
        <header class="pt-1">
            <h4>
                <ui:insert name="title">
                    Shop
                </ui:insert>
            </h4>
        </header>
    </div>
</ui:composition>

web/src/main/webapp/inc/login.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:p="http://primefaces.org/ui"
>
    <h:form>
        <p:panel header="PrimeFaces Hello World Example">
            <h:panelGrid columns="2" cellpadding="4">
                <h:outputText value="First Name: "/>
                <p:inputText value="#{greetingService.firstName}"/>

                <h:outputText value="Last Name: "/>
                <p:inputText value="#{greetingService.lastName}"/>

                <p:commandButton value="Submit" update="greeting"
                                 oncomplete="PF('greetingDialog').show()"/>
            </h:panelGrid>
        </p:panel>

        <p:dialog header="Greeting" widgetVar="greetingDialog"
                  modal="true" resizable="false">
            <h:panelGrid id="greeting" columns="1" cellpadding="4">
                <h:outputText value="#{greetingService.showGreeting()}"/>
            </h:panelGrid>
        </p:dialog>
    </h:form>
</ui:composition>

web/src/main/webapp/inc/menu.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ul>
        <li>
            <h:link value="Shop" outcome="shop" />
        </li>
        <li>
            <h:link value="Cart" outcome="cart" />
        </li>
        <li>
            <h:link value="Orders" outcome="orders" />
        </li>
    </ul>

    <hr/>
    Products
    <ul>
        <li>
            <h:link value="Create" outcome="productCreate" />
        </li>
    </ul>
</ui:composition>

web/src/main/webapp/inc/messages.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html">

    <div class="container">
        <div class="alert alert-dark">
            <h:messages id="errors"
                        infoStyle="color: blue;"
                        warnStyle="color: orange;"
                        errorStyle="color: red;"/>
        </div>
    </div>
</ui:composition>

web/src/main/webapp/layouts/app.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<h:head>
    <title><ui:insert name="title">Shop</ui:insert></title>
    <link href="#{request.contextPath}/assets/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</h:head>
<h:body>
    <ui:include src="../inc/messages.xhtml"/>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <ui:include src="../inc/content.xhtml"/>
            </div>

            <div class="col-md-3">
                <ui:include src="../inc/header.xhtml"/>

                <ui:include src="../inc/menu.xhtml"/>
            </div>
        </div>
    </div>

    <ui:include src="../inc/footer.xhtml"/>

    <!--<script src="#{request.contextPath}/assets/libs/bootstrap/js/jquery-3.2.1.slim.min.js"></script>-->
    <!--<script src="#{request.contextPath}/assets/libs/bootstrap/js/bootstrap.min.js"></script>-->
    <!--<script src="#{request.contextPath}/assets/libs/bootstrap/js/popper.min.js"></script>-->
</h:body>
</html>

web/src/main/webapp/orders.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
>
<ui:composition template="layouts/app.xhtml">
    <f:metadata>
        <f:viewAction action="#{productBean.availableList}"/>
    </f:metadata>

    <ui:define name="title">Shop</ui:define>
    <ui:define name="content">
        <ui:include src="products/filter.xhtml"/>

        <p:dataTable id="productsTable"
                     value="#{orderBean.all}"
                     var="order"
                     styleClass="table"
        >
            <p:column>
                <h:outputText value="#{order.id}/#{order.createdAt}"/>
            </p:column>
            <p:column>
                <ui:include src="products/table.xhtml">
                    <ui:param name="products" value="#{order.products}" />
                </ui:include>
            </p:column>

        </p:dataTable>
    </ui:define>
</ui:composition>
</html>

web/src/main/webapp/productCreate.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
>
<ui:composition template="layouts/app.xhtml">
    <ui:define name="title">Product Craete</ui:define>
    <ui:define name="content">

        <h:form id="productForm">
            <h:panelGrid columns="2" styleClass="table">
                <f:facet name="header">
                    <h:message for="name"/>
                    <br/>
                    <h:message for="price"/>
                    <br/>
                    <h:message for="body"/>
                </f:facet>

                <h:outputLabel value="Name :"/>
                <h:inputText id="name" value="#{productBean.newProduct.name}"/>

                <h:outputLabel value="Price : "/>
                <h:inputText id="price" value="#{productBean.newProduct.price}" converter="bigDecimalConverter">
                </h:inputText>

                <h:outputLabel value="Body :"/>
                <h:inputText id="body" value="#{productBean.newProduct.body}"/>
            </h:panelGrid>
            <h:commandButton
                    value="Create a product"
                    action="#{productBean.create}"
                    styleClass="btn btn-success"
            />
        </h:form>
    </ui:define>
</ui:composition>
</html>

web/src/main/webapp/productView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
>
<ui:composition template="layouts/app.xhtml">
    <f:metadata>
        <f:viewParam name="id" value="#{productBean.currentProduct.id}"/>
        <f:viewAction action="#{productBean.findByById}"/>
    </f:metadata>

    <ui:define name="title">
        View Product
    </ui:define>

    <ui:define name="content">
        <h4>
            <h:outputText value="#{productBean.currentProduct.name}"/>
        </h4>

        <ui:include src="products/table.xhtml">
            <ui:param name="products" value="#{productBean.currentProduct}"/>
            <ui:param name="canAddToCart" value="false"/>
            <ui:param name="showPagination" value="false"/>
        </ui:include>

        <div class="alert alert-light">
            <h:outputText value="#{productBean.currentProduct.body}"/>
        </div>
    </ui:define>
</ui:composition>
</html>

web/src/main/webapp/products/filter.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html"
>
    <i class="badge">Filter</i>

    <h:form>
        <table class="table">
            <tr>
                <td>
                    <h:outputLabel value="Name:"/>
                </td>
                <td style="width: 30px;">
                    <h:outputLabel value="Price From:"/>
                </td>
                <td style="width: 30px;">
                    <h:outputLabel value="Price To:"/>
                </td>
            </tr>
            <tr>
                <td>
                    <h:inputText id="name" value="#{productBean.criteria.name}"/>
                </td>
                <td>
                    <!--<h:inputText id="priceFrom" value="#{productBean.criteria.priceFrom}">-->
                    <h:inputText id="priceFrom" value="#{productBean.criteria.priceFrom}" converter="bigDecimalConverter">
                        <!--<f:convertNumber pattern="#0.000"/>-->
                    </h:inputText>
                </td>
                <td>
                    <!--<h:inputText id="priceTo" value="#{productBean.criteria.priceTo}">-->
                    <h:inputText id="priceTo" value="#{productBean.criteria.priceTo}" converter="bigDecimalConverter">
                        <!--<f:convertNumber pattern="#0.000"/>-->
                    </h:inputText>
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>
                    <div class="btn-group-justified">
                        <h:commandButton value="Search" action="#{productBean.search}"/>
                        <h:commandButton value="Clear" action="#{productBean.clear}"/>
                    </div>
                </td>
            </tr>
        </table>
    </h:form>
    <hr/>
</ui:composition>

web/src/main/webapp/products/table.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:p="http://primefaces.org/ui"
>
    <p:dataTable id="productsTable"
                 value="#{products}"
                 var="product"
                 styleClass="table"
                 paginator="#{showPagination}"
                 rows="20"
                 paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                 currentPageReportTemplate="{startRecord} - {endRecord} of {totalRecords}"
                 rowsPerPageTemplate="5,10,15"

    >
        <p:column>
            <h:graphicImage value="#{product.photo}"/>
        </p:column>
        <p:column>
            <h:link value="#{product.name}" outcome="productView">
                <f:param name="id" value="#{product.id}"/>
            </h:link>
        </p:column>
        <p:column>
            <f:facet name="header">+</f:facet>

            <h:form rendered="#{canAddToCart}">
                <h:commandButton value="$#{product.price}"
                                 action="#{cartBean.addToCart(product)}"
                                 type="submit"
                                 styleClass="btn btn-dark"/>
            </h:form>

            <h:outputText value="$#{product.price}" rendered="#{!canAddToCart}"/>
        </p:column>
    </p:dataTable>
</ui:composition>

web/src/main/webapp/shop.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://xmlns.jcp.org/jsf/html"
>
<ui:composition template="layouts/app.xhtml">
    <f:metadata>
        <f:viewAction action="#{productBean.availableList}"/>
    </f:metadata>

    <ui:define name="title">Shop</ui:define>
    <ui:define name="content">
        <ui:include src="products/filter.xhtml"/>
        <ui:include src="products/table.xhtml">
            <ui:param name="products" value="#{productBean.productList}" />
            <ui:param name="canAddToCart" value="true" />
            <ui:param name="showPagination" value="true" />
        </ui:include>
    </ui:define>
</ui:composition>
</html>